### ISSUE TITLE
Unable to resolve type MaterialIcon

### ISSUE THREAD

**Issue by PerfectlyFineCode** [SKProCH/Material.Icons#33]
This error crashes JetBrains Rider Avalonia previewer.

Rider:
```
  JetBrains Rider 2023.3.4
  Build #RD-233.14475.66, built on March 6, 2024
  Runtime version: 17.0.10+1-b1087.17 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  Windows 11.
  avalonia-rider (1.3.0)
```

```xml
<PackageReference Include="Material.Icons.Avalonia" Version="2.1.9" />
```

```xml
2024-04-12 17:17:18,850 [  19198]   WARN - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - XAML update error: XamlParseException at 29:26: Unable to resolve type MaterialIcon from namespace clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia Line 29, position 26.
XamlX.XamlParseException: Unable to resolve type MaterialIcon from namespace clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia Line 29, position 26.
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstXamlPropertyValueNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Transform.AstTransformationContext.Visit(IXamlAstNode root, IXamlAstTransformer transformer)
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
```

No idea whether this is library related or a bug with Avalonia itself. I have previously made an issue on Avalonia preview repo, but they directed me towards Avalonia themselves or the library (Material.Icons.Avalonia)

**Comment by SKProCH** [comment]
Hello, @PerfectlyFineCode 

Did it works when you just launch you app as usual?

**Comment by PerfectlyFineCode** [comment]
> Hello, @PerfectlyFineCode 
> 
> Did it works when you just launch you app as usual?

Yes.

**Comment by SKProCH** [comment]
So, this is a previewer issue.

**Comment by SKProCH** [comment]
You probably should report it to Avalonia
